### PR TITLE
Bump min deployment target

### PR DESCRIPTION
**Pull request by bozhchenko**
Update ios and tvos deployment targets to 12.

### CODE REVIEW

**Review by atomlife — COMMENTED** [review]
I lint'd this successfully if we ignore warnings. I think the warnings are directly related to deprecated code as of iOS 12

```
    - WARN  | xcodebuild:  /Users/amiller/libPhoneNumber-iOS/libPhoneNumber/NBPhoneNumberUtil.m:3482:51: warning: 'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0 [-Wdeprecated-declarations]
   
```

can you double check that this is ok and we're not breaking anything by brining in the deprecated code?

**Comment by bozhchenko** [comment]
> I lint'd this successfully if we ignore warnings. I think the warnings are directly related to deprecated code as of iOS 12
> 
> ```
>     - WARN  | xcodebuild:  /Users/amiller/libPhoneNumber-iOS/libPhoneNumber/NBPhoneNumberUtil.m:3482:51: warning: 'subscriberCellularProvider' is deprecated: first deprecated in iOS 12.0 [-Wdeprecated-declarations]
>    
> ```
> 
> can you double check that this is ok and we're not breaking anything by brining in the deprecated code?

Hey @atomlife.
If I change deprecated func to new one - I need to understand how should I use new func in valid way.
The thing is that starting from iOS 12 we should take care about eSim as well and we could have many `subscriberCellularProviders`.
More context could be found here - https://stackoverflow.com/q/61669237

The simplest solution is 
```
NSString * _Nullable isoCode;
    for (CTCarrier * subscriberCellularProvider in [self.telephonyNetworkInfo serviceSubscriberCellularProviders]) {
        if (isoCode.length == 0) {
            isoCode = [subscriberCellularProvider isoCountryCode];
        }
 }
```
But I am not sure about it, maybe we should refactor that in more extended way as user could have diff `isoCountryCodes`.

cc: @roman-ivchenko-973

**Comment by atomlife** [comment]
@bozhchenko In that case the important thing is to make sure the deprecated function was deprecated in a way that lets it continue to "work" with our app. Often a deprecation is more than just a deprecation and functionality is removed. I wanted to know if this would continue to work.

**Comment by bozhchenko** [comment]
> @bozhchenko In that case the important thing is to make sure the deprecated function was deprecated in a way that lets it continue to "work" with our app. Often a deprecation is more than just a deprecation and functionality is removed. I wanted to know if this would continue to work.

Hey @atomlife we can continue use deprecated `subscriberCellularProvider`, as I got it from Apple forums and also from debug prints.
It works like `serviceSubscriberCellularProviders [0]` under the hood.
Here you could read more details: https://forums.developer.apple.com/forums/thread/714876?page=2

But as for me - will be nice to take care about this deprecation more deeply, by creating technical debt ticket for that. What do you think about it?

**Comment by bozhchenko** [comment]
> subscriberCellularProvider

One more thing regarding deprecated `subscriberCellularProvider` func. Originally it was deprecated from iOS 12, so if this deprecation had caused some issue - we would have got a lot of bugs.
Is it make sense for you as well? I hope :)

**Review by atomlife — APPROVED** [review]

**Comment by atomlife** [comment]
LGTM. Let me know when the release is up and I will push the podspec. Thank you for doing all those extra steps @bozhchenko

**Pull request merged**
